spring:
  application:
    name: workshop-employee
  datasource:
    url: jdbc:postgresql://localhost:5432/ompalompa
    username: user
    password: local-no-so-secret
  jpa:
    hibernate:
      ddl-auto: update



employee:
  description:
    mandatory: false


management:
  endpoints:
    web:
      exposure:
        include: health, refresh
