spring:
  application:
    name: Employee
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
    redis:
      time-to-live: PT60S
      key-prefix: "${spring.application.name}:"