version: '3'

services:
  redis:
    image: redis
    ports:
      - 6311:6379
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mysupersecretpassword
      - RABBITMQ_DEFAULT_VHOST=shortener
    ports:
      - 14472:15672
      - 4472:5672